version: '3'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Thelema77,
    logging:
      driver: 'none'
  web:
    build: .
    command: ./start_server.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
